region           = "eu-west-2"
environment      = "prod"
business_unit    = "lch"
application_name = "sno"
application_id   = "APP-12345"
cost_centre      = "cc12345"
project_code     = "12345-1234"
default_vpc_name = "SNO-POC-POC-vpc"
